# Project Funding

Thank you for considering supporting the Lushai (Mizo) Translation Project! Your contributions will help us in our mission to bring the Lushai (Mizo) language to Telegram and promote its preservation and growth.

## How to Support

'We offer several ways to support our project financially. You can choose any of the following platforms to make a contribution :

github: @lalrochhara
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: @NickyLrca
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: @NickyLrca
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

Your support will help us in maintaining and improving the Lushai (Mizo) translations for Telegram, making it more accessible to Lushai (Mizo)-speaking communities worldwide.

We are grateful for any contribution you can make, big or small. It will go a long way in advancing our project and fostering the Lushai (Mizo) language.

Thank you for being a part of the Lushai (Mizo) Translation Project!
